"""
Gap 1: Compute |F+|/|F-| during DS evolution on a 4D lattice.
Verify chirality balance and its dependence on K.

Key insight: F+ is generated by the Born floor DURING the transient.
At equilibrium, the floor is inactive and F+=F-=0 (trivially balanced).
The real test is: does |F+|=|F-| during the transient when F is nonzero?
"""
import numpy as np
from numpy.linalg import det, inv

I2 = np.eye(2, dtype=complex)
s1m = np.array([[0, 1], [1, 0]], dtype=complex)
s2m = np.array([[0, -1j], [1j, 0]], dtype=complex)
s3m = np.array([[1, 0], [0, -1]], dtype=complex)

H = 3
BORN_FLOOR = 1.0 / H**3

def mass_to_M(mass):
    return (mass[3]*I2 + mass[0]*s1m + mass[1]*s2m + mass[2]*s3m) / np.sqrt(2)

def enforce_born_floor(mass, floor=BORN_FLOOR):
    m2 = np.abs(mass)**2
    S = np.sum(m2)
    if S < 1e-15: return mass, False
    if m2[3] / S >= floor: return mass, False
    lo, hi = 0.0, 1.0
    for _ in range(50):
        mid = (lo + hi) / 2
        trial = mass.copy()
        trial[:3] *= mid
        trial[3] = 1.0 - np.sum(trial[:3])
        t2 = np.abs(trial)**2
        St = np.sum(t2)
        bt = t2[3] / St if St > 0 else 1.0
        if bt < floor: hi = mid
        else: lo = mid
    result = mass.copy()
    result[:3] *= lo
    result[3] = 1.0 - np.sum(result[:3])
    return result, True

def ds_combine(m1, m2):
    s1, th1 = m1[:3], m1[3]
    s2, th2 = m2[:3], m2[3]
    s_new = s1*s2 + s1*th2 + th1*s2
    th_new = th1*th2
    K = np.sum(s1)*np.sum(s2) - np.sum(s1*s2)
    n = 1.0 - K
    if abs(n) < 1e-15: n = 1e-15
    return np.append(s_new, th_new) / n, K

def compute_curvature(lattice, L):
    """Compute |F+|^2 and |F-|^2 using 4D Hodge decomposition."""
    planes = [(0,1), (0,2), (0,3), (1,2), (1,3), (2,3)]
    F_plus_sq = 0.0
    F_minus_sq = 0.0

    for idx in np.ndindex(L, L, L, L):
        # Compute F_mu_nu for all 6 planes
        F_arr = np.zeros((6, 2, 2), dtype=complex)

        for p, (mu, nu) in enumerate(planes):
            pos = list(idx)

            M00 = mass_to_M(lattice[idx])
            d00 = det(M00)
            if abs(d00) < 1e-15: continue

            pos_mu = list(idx); pos_mu[mu] = (pos_mu[mu]+1)%L
            pos_nu = list(idx); pos_nu[nu] = (pos_nu[nu]+1)%L
            pos_munu = list(idx); pos_munu[mu] = (pos_munu[mu]+1)%L; pos_munu[nu] = (pos_munu[nu]+1)%L

            M10 = mass_to_M(lattice[tuple(pos_mu)])
            M01 = mass_to_M(lattice[tuple(pos_nu)])
            M11 = mass_to_M(lattice[tuple(pos_munu)])

            iM00 = inv(M00)
            U_mu = M10 @ iM00
            U_nu = M01 @ iM00

            d01 = det(M01)
            d10 = det(M10)
            if abs(d01) < 1e-15 or abs(d10) < 1e-15: continue

            U_nu_at_mu = M11 @ inv(M10)
            U_mu_at_nu = M11 @ inv(M01)

            plaq = U_mu @ U_nu_at_mu @ inv(U_mu_at_nu) @ inv(U_nu)
            F_arr[p] = plaq - I2

        # 4D Hodge star
        starF = np.array([
            F_arr[5],   # *01 = 23
            -F_arr[4],  # *02 = -13
            F_arr[3],   # *03 = 12
            F_arr[2],   # *12 = 03
            -F_arr[1],  # *13 = -02
            F_arr[0],   # *23 = 01
        ])

        Fplus = (F_arr + starF) / 2
        Fminus = (F_arr - starF) / 2

        F_plus_sq += np.sum(np.abs(Fplus)**2)
        F_minus_sq += np.sum(np.abs(Fminus)**2)

    return F_plus_sq, F_minus_sq


# === Main computation ===
L = 4
np.random.seed(42)

print("Initializing 4^4 lattice with random complex mass functions...")
lattice = np.zeros((L, L, L, L, 4), dtype=complex)
for idx in np.ndindex(L, L, L, L):
    s = np.random.rand(3) * 0.3 + 0.15j * np.random.randn(3)
    lattice[idx] = np.append(s, 1 - np.sum(s))

print()
print(f"{'sweep':>5s} {'Re(K)':>10s} {'|Im(K)|':>10s} {'floor%':>8s} {'|F+|^2':>12s} {'|F-|^2':>12s} {'|F+|/|F-|':>10s}")

for sweep in range(50):
    # Measure curvature BEFORE this sweep
    if sweep % 2 == 0:
        Fp, Fm = compute_curvature(lattice, L)
        ratio = np.sqrt(Fp/Fm) if Fm > 1e-30 else 0.0

    # DS update
    new_lattice = lattice.copy()
    K_vals = []
    floor_count = 0
    total_sites = 0

    for idx in np.ndindex(L, L, L, L):
        neighbors = []
        for mu in range(4):
            pos_p = list(idx); pos_p[mu] = (pos_p[mu]+1)%L
            pos_m = list(idx); pos_m[mu] = (pos_m[mu]-1)%L
            neighbors.append(lattice[tuple(pos_p)])
            neighbors.append(lattice[tuple(pos_m)])
        e = np.mean(neighbors, axis=0)
        e_sum = np.sum(e)
        if abs(e_sum) > 1e-15:
            e = e / e_sum
        m_new, K = ds_combine(lattice[idx], e)
        m_new, active = enforce_born_floor(m_new)
        new_lattice[idx] = m_new
        K_vals.append(K)
        if active: floor_count += 1
        total_sites += 1

    lattice = new_lattice
    K_mean = np.mean(K_vals)
    imK = np.mean(np.abs(np.imag(K_vals)))
    fl_pct = floor_count / total_sites * 100

    if sweep % 2 == 0:
        print(f"{sweep:5d} {K_mean.real:10.6f} {imK:10.6f} {fl_pct:7.1f}% {Fp:12.6f} {Fm:12.6f} {ratio:10.4f}")

# Final measurement
Fp, Fm = compute_curvature(lattice, L)
ratio = np.sqrt(Fp/Fm) if Fm > 1e-30 else 0.0
print(f"{'final':>5s} {'':>10s} {'':>10s} {'':>8s} {Fp:12.6f} {Fm:12.6f} {ratio:10.4f}")

print()
print("=== SUMMARY ===")
print(f"K* = 7/30 = {7/30:.6f}")
print(f"Final Re(K) = {K_mean.real:.6f}")
print(f"|F+|/|F-| during transient (where floor is active and F != 0)")
