"""
Gluon condensate v2: Use gauge-derived evidence e* (not neighbours).

The physical equilibrium is NOT self-evidence (K=0, F=0).
It's the K*=7/30 equilibrium with gauge-derived evidence e* != m*.

The condensate <F^2> comes from spatial FLUCTUATIONS of m(x) around m*,
where each site is driven by e* (the conditional distribution C_beta).
The spatial variation of m(x) generates nonzero connection a = M^{-1}dM
and hence nonzero curvature.

Strategy:
1. Initialize lattice with random perturbations around m*
2. Evolve with FIXED evidence e* (not neighbour average) for a few steps
   to thermalize — but DON'T fully converge (that kills all fluctuations)
3. The thermal state has spatial fluctuations around m*
4. Measure F^2 from the spatial variation

The key insight: the condensate is the curvature generated by the
SPATIAL INHOMOGENEITY of the mass function field. At exact equilibrium
(uniform m* everywhere), F=0. The path integral averages over all
configurations m(x) weighted by the DS dynamics, most of which have
m(x) varying spatially.
"""

import numpy as np
from numpy.linalg import inv, norm, det
from itertools import product as iprod
from scipy.optimize import brentq
import sys

H = 3; FLOOR = 1.0/27.0

sigma = [
    np.array([[0,1],[1,0]], dtype=complex),
    np.array([[0,-1j],[1j,0]], dtype=complex),
    np.array([[1,0],[0,-1]], dtype=complex)
]

def enforce_floor(m):
    s = m[:3].copy(); th = m[3]
    born = th**2 / (np.sum(s**2) + th**2)
    if born >= FLOOR: return m.copy()
    S = np.sum(s); Sq = np.sum(s**2); R = Sq/S**2
    t = (np.sqrt(26*R) - R)/(26-R); alpha = (1-t)/S
    out = m.copy(); out[:3] = s*alpha; out[3] = t
    return out

def ds_combine(m, e):
    s,th = m[:3],m[3]; se,ph = e[:3],e[3]
    sn = s*se + s*ph + th*se; tn = th*ph
    K = sum(s[i]*se[j] for i in range(3) for j in range(3) if i!=j)
    d = 1-K; out = np.zeros(4); out[:3]=sn/d; out[3]=tn/d
    return enforce_floor(out), K

def to_matrix(m):
    s1,s2,s3,th = m
    return (th*np.eye(2,dtype=complex) + s1*sigma[0] + s2*sigma[1] + s3*sigma[2]) / np.sqrt(2)

def find_eq():
    def K_res(p):
        pw=(1-p)/2; sc=26./27.
        raw = np.array([np.sqrt(p*sc), np.sqrt(pw*sc), np.sqrt(pw*sc), np.sqrt(FLOOR)])
        e = raw/np.sum(raw); m = np.array([0.4,0.2,0.2,0.2])
        for _ in range(3000): m,_ = ds_combine(m,e)
        K = sum(m[i]*e[j] for i in range(3) for j in range(3) if i!=j)
        return K - 7./30.
    p = brentq(K_res, 0.92, 0.94, xtol=1e-15)
    pw=(1-p)/2; sc=26./27.
    raw = np.array([np.sqrt(p*sc), np.sqrt(pw*sc), np.sqrt(pw*sc), np.sqrt(FLOOR)])
    e = raw/np.sum(raw); m = np.array([0.4,0.2,0.2,0.2])
    for _ in range(3000): m,_ = ds_combine(m,e)
    return m, e

m_star, e_star = find_eq()
print(f"m* = {m_star}")
print(f"e* = {e_star}")
print(f"K(m*,e*) = {sum(m_star[i]*e_star[j] for i in range(3) for j in range(3) if i!=j):.6f}")
print(); sys.stdout.flush()

N = 12

# ============================================================
# The path integral: sample configurations, measure F^2
# ============================================================
#
# Each "configuration" is a lattice of mass functions m(x).
# The weight is the DS dynamics: configurations near m* are weighted
# by how quickly DS drives toward m*.
#
# For a Monte Carlo estimate: start from random initial conditions,
# evolve a few steps with e* evidence (to approach m* but retain
# spatial variation), measure F^2.
#
# The NUMBER of DS steps determines the "temperature": fewer steps =
# more fluctuation = larger <F^2>. In the path integral language,
# the transfer matrix T = e^{-H} acts for n steps, projecting onto
# low-energy states. At finite n, there's a thermal mixture.
#
# The correct <F^2> is the n->infinity LIMIT where only the ground
# state survives — but the ground state is uniform m*, which has F=0.
# So <F^2> in the vacuum = 0?
#
# No. The point is more subtle. In the path integral:
# <F^2> = integral over ALL configurations of F^2(config) * weight(config)
#
# Even though the dominant configuration (m* uniform) has F=0,
# the fluctuations around it have F != 0, and their contribution
# to the average is nonzero.
#
# The Schwinger function S_2^c(0) = <F^2> - <F>^2 = <F^2> (since <F>=0).
# This equals sum_k |c_k|^2 from the spectral decomposition.
# The coefficients c_k come from the overlap of F^2 with the eigenvectors.
#
# So <F^2> = sum_k |<psi_k|F^2|vacuum>|^2 * lambda_k^0 = sum_k |c_k|^2.
# This is a FINITE sum because the state space is compact.
#
# The computation: sample m ~ FS measure on B, compute F^2(m, neighbours),
# average. The FS measure samples uniformly from B, which IS the path
# integral measure at t=0 (before any DS evolution).

print("="*60)
print("GLUON CONDENSATE via Fubini-Study sampling on B")
print("="*60)
print(); sys.stdout.flush()

def sample_from_B(n_samples, m_center, sigma_pert):
    """Sample mass functions from a neighbourhood of m_center in B."""
    samples = []
    for _ in range(n_samples):
        perturb = sigma_pert * np.random.randn(4)
        m = m_center + perturb
        m = np.abs(m)
        m /= np.sum(m)
        m = enforce_floor(m)
        samples.append(m)
    return samples

def compute_F_sq_lattice(lattice, N):
    """Compute <F^2> across the lattice."""
    F_sq_total = 0.0
    n_sites = 0

    for ix,iy,iz in iprod(range(N), repeat=3):
        M = to_matrix(lattice[ix,iy,iz])
        Mi = inv(M)

        a = []
        for d in range(3):
            ip=[ix,iy,iz]; im=[ix,iy,iz]
            ip[d]=(ip[d]+1)%N; im[d]=(im[d]-1)%N
            Mp = to_matrix(lattice[tuple(ip)])
            Mm = to_matrix(lattice[tuple(im)])
            a.append(Mi @ (Mp - Mm) / 2.0)

        for mu in range(3):
            for nu in range(mu+1, 3):
                comm = a[mu] @ a[nu] - a[nu] @ a[mu]

                # Plaquette: use Wilson loop around elementary square
                # U_plaq = M(x)^{-1} M(x+mu) M(x+mu)^{-1}M(x+mu+nu) ...
                # Simpler: use F = [a_mu, a_nu] as leading order
                # (the da term is second order in the perturbation)

                F_mn = comm  # leading order
                F_sq_total += np.real(np.trace(F_mn.conj().T @ F_mn))

        n_sites += 1

    return F_sq_total / n_sites

# Generate many random lattice configurations and measure F^2
n_configs = 50
sigmas = [0.005, 0.01, 0.02, 0.05, 0.1, 0.15, 0.2]

print(f"Sampling {n_configs} configurations per amplitude on {N}^3 lattice")
print()

for sig in sigmas:
    F2_samples = []
    for config in range(n_configs):
        np.random.seed(config * 1000 + int(sig * 10000))
        lat = np.zeros((N,N,N,4))
        for ix,iy,iz in iprod(range(N), repeat=3):
            perturb = sig * np.random.randn(4)
            m = m_star + perturb
            m = np.abs(m); m /= np.sum(m)
            lat[ix,iy,iz] = enforce_floor(m)

        F2 = compute_F_sq_lattice(lat, N)
        F2_samples.append(F2)

    F2_arr = np.array(F2_samples)
    print(f"  sigma={sig:.3f}: <F^2> = {np.mean(F2_arr):.8f} +/- {np.std(F2_arr)/np.sqrt(n_configs):.8f}")
    sys.stdout.flush()

print()

# Now: what does <F^2> look like as a function of the number of DS steps?
# Start from a random config, evolve with e*, measure F^2 at each step.
print("="*60)
print("<F^2> vs DS evolution steps (with e* evidence)")
print("="*60)
print()

np.random.seed(42)
lat = np.zeros((N,N,N,4))
for ix,iy,iz in iprod(range(N), repeat=3):
    perturb = 0.1 * np.random.randn(4)
    m = m_star + perturb
    m = np.abs(m); m /= np.sum(m)
    lat[ix,iy,iz] = enforce_floor(m)

F2_initial = compute_F_sq_lattice(lat, N)
print(f"Step 0: <F^2> = {F2_initial:.8f}")

for step in range(1, 31):
    lat_new = np.zeros_like(lat)
    for ix,iy,iz in iprod(range(N), repeat=3):
        lat_new[ix,iy,iz], _ = ds_combine(lat[ix,iy,iz], e_star)
    lat = lat_new

    F2 = compute_F_sq_lattice(lat, N)
    dev = np.max([norm(lat[ix,iy,iz] - m_star) for ix,iy,iz in iprod(range(N), repeat=3)])
    print(f"Step {step:2d}: <F^2> = {F2:.8f}, max|m-m*| = {dev:.6f}")
    sys.stdout.flush()

print()
print("="*60)
print("INTERPRETATION")
print("="*60)
print()
print("If <F^2> decays to 0 as steps -> infinity:")
print("  The vacuum has <F^2> = 0. No condensate at the fixed point.")
print("  The condensate is a property of the path integral measure,")
print("  not the vacuum state. <F^2>_PI = integral over B of F^2 * d(FS),")
print("  which is nonzero because most of B has spatial variation.")
print()
print("If <F^2> stabilizes at a nonzero value:")
print("  The thermal equilibrium retains spatial inhomogeneity.")
print("  The condensate is dynamically generated.")
print()
print("DONE.")
