#!/usr/bin/env python3
"""Check K under simultaneous rotation of both m and e."""
import numpy as np

s1, s2, s3 = 0.78690, 0.02928, 0.02928
e1, e2, e3 = 0.63120, 0.12030, 0.12030
S = s1+s2+s3; E = e1+e2+e3
agree = s1*e1 + s2*e2 + s3*e3
K = S*E - agree
print(f"Original: S={S:.6f}, E={E:.6f}, agree={agree:.6f}, K={K:.6f}")
print()

# Rotate BOTH by same angle phi in s2-s3 plane
# (generated by sigma_1 = the Pauli rotation)
print("Rotating BOTH m* and e* simultaneously in s2-s3 plane:")
for phi in [0, np.pi/6, np.pi/4, np.pi/3, np.pi/2, 2*np.pi/3, np.pi]:
    c, sa = np.cos(phi), np.sin(phi)
    s2r = c*s2 - sa*s3
    s3r = sa*s2 + c*s3
    e2r = c*e2 - sa*e3
    e3r = sa*e2 + c*e3

    Sr = s1 + s2r + s3r
    Er = e1 + e2r + e3r
    agr = s1*e1 + s2r*e2r + s3r*e3r
    Kr = Sr*Er - agr

    print(f"  phi={phi/np.pi:.3f}pi: S={Sr:.6f}, E={Er:.6f}, agree={agr:.6f}, K={Kr:.6f}, ΔK={Kr-K:+.4e}")

print()
# The analytical reason S changes:
# S = s1 + s2*cos(phi) - s3*sin(phi) + s2*sin(phi) + s3*cos(phi)
# = s1 + s2*(cos+sin) + s3*(cos-sin)
# At s2=s3=a: S = s1 + 2a*cos(phi) -- varies with phi!
print("Analytical: S = s1 + 2*s2*cos(phi) for s2=s3:")
for phi in [0, np.pi/4, np.pi/2, np.pi]:
    print(f"  phi={phi/np.pi:.2f}pi: S_analytic = {s1 + 2*s2*np.cos(phi):.6f}")

print()
# Now check: does the PERMUTATION s2<->s3, e2<->e3 preserve K?
# (this is phi=pi/2 in a permutation sense, NOT a continuous rotation)
s2p, s3p = s3, s2  # permute
e2p, e3p = e3, e2
Sp = s1+s2p+s3p
Ep = e1+e2p+e3p
agrp = s1*e1 + s2p*e2p + s3p*e3p
Kp = Sp*Ep - agrp
print(f"Under permutation s2<->s3, e2<->e3: K={Kp:.6f} (vs original {K:.6f})")
print(f"  ΔK = {Kp-K:.2e} -- {'INVARIANT' if abs(Kp-K)<1e-10 else 'CHANGES'}")
